# Generated by Django 2.2.9 on 2020-08-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('naver', 'Naver'), ('google', 'Google'), ('kakao', 'Kakao')], default='naver', max_length=50),
        ),
    ]
