# Generated by Django 2.2.9 on 2020-08-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200819_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('naver', 'Naver'), ('google', 'Google'), ('kakao', 'Kakao')], default='kakao', max_length=50),
        ),
    ]
