# Generated by Django 2.2.9 on 2020-08-06 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='name',
        ),
    ]
