# Generated by Django 2.2.9 on 2020-08-06 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0002_auto_20200806_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='shop',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='shops.Shop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ManyToManyField(related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
