# Generated by Django 2.2.9 on 2020-08-06 03:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0002_auto_20200806_1059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.AddField(
            model_name='shop',
            name='favorite',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
