# Generated by Django 2.2.9 on 2020-08-06 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0002_shop_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='average',
            field=models.IntegerField(blank=True, default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='like_users',
            field=models.ManyToManyField(related_name='like_shops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rating', models.SmallIntegerField(blank=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops_rating', to='shops.Shop')),
                ('user', models.ManyToManyField(related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
