# Generated by Django 2.2.9 on 2020-08-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20200806_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='homepage',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='region',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
