# Generated by Django 2.2.9 on 2020-08-06 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20200806_1209'),
        ('shops', '0003_auto_20200806_1212'),
    ]

    operations = [
    ]
