# Generated by Django 2.2.9 on 2020-08-06 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0004_auto_20200806_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='average',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='shop',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops_rating', to='shops.Shop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ManyToManyField(related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='shops.Shop'),
        ),
    ]
