# Generated by Django 2.2.9 on 2020-08-06 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_auto_20200806_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='total',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
    ]
