# Generated by Django 2.2.9 on 2020-08-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_auto_20200806_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='average',
        ),
        migrations.AddField(
            model_name='shop',
            name='average',
            field=models.IntegerField(blank=True, default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.SmallIntegerField(blank=True),
        ),
    ]
