# Generated by Django 2.2.9 on 2020-08-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='shop',
            field=models.ManyToManyField(blank=True, related_name='cars', to='shops.Shop'),
        ),
    ]
