# Generated by Django 2.2.9 on 2020-08-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='shop',
            field=models.ManyToManyField(blank=True, related_name='cars', related_query_name='car', to='shops.Shop'),
        ),
    ]
